name: 'CrazyCrates'
main: '${group}.CrazyCrates'

authors: [BadBones69, RyderBelserion]

version: '${version}'
api-version: '1.20'
description: '${description}'
website: '${website}'

softdepend: [CMI, HolographicDisplays, DecentHolograms, PlaceholderAPI, ItemsAdder]

commands:
  crazycrates:
    description: The base command for Crazy Crates
  keys:
    description: Views the amount of keys you/others have.