[versions]

# Paper
paper = "1.19.2-R0.1-SNAPSHOT"
paper-command-cloud = "1.7.0"
paper-lib = "1.0.8-SNAPSHOT"

# Fabric
minecraft-version = "1.19.2"

yarn-mappings = "1.19.2+build.9"
loader-version = "0.14.9"

fabric-version = "0.60.0+1.19.2"

# Misc
bstats = "3.0.0"
nbt-api = "2.10.0"

# Holograms
holographic-displays = "2.4.9"
decent-holograms = "2.7.2"

# Placeholders
placeholder-api = "2.11.2"

# Misc Libraries
vault-api = "1.7"
adventure-api = "4.11.0"

# Triumph Team
gui = "3.1.2"

# Common Versions
gson = "2.9.1"

apache = "3.12.0"

# Simple YAML
yaml = "1.8.1"

[libraries]

# PaperMC
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
paper-command-cloud = { module = "cloud.commandframework:cloud-paper", version.ref = "paper-command-cloud" }
paper-lib = { module = "io.papermc:paperlib", version.ref = "paper-lib" }

# FabricMC
fabric-minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft-version" }
fabric-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader-version" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-version" }

# BStats Bukkit
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

# Holograms
holographic-displays = { module = "com.gmail.filoghost.holographicdisplays:holographicdisplays-api", version.ref = "holographic-displays" }
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decent-holograms" }

# Placeholders
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }

# NBT API Libraries
nbt-api = { module = "de.tr7zw:nbt-data-api", version.ref = "nbt-api" }

# Misc Libraries
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault-api" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }

# Triumph Team
triumph-gui-bukkit = { module = "dev.triumphteam:triumph-gui", version.ref = "gui" }

# Common Libraries
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

apache-commons = { module = "org.apache.commons:commons-lang3", version.ref = "apache" }

# Simple YAML
simple-yaml = { module = "me.carleslc.Simple-YAML:Simple-Yaml", version.ref = "yaml" }