[versions]

# Minecraft
paper = "1.19.3-R0.1-SNAPSHOT"

# Adventure
adventure = "4.12.0"

# RubyCore
ruby = "1.0.0.0"
yaml = "1.8.3"

[libraries]

# Minecraft
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Adventure
adventure_api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure_text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

# RubyCore
ruby_api = { module = "net.dehya.ruby:ruby-core", version.ref = "ruby" }
ruby_paper = { module = "net.dehya.ruby:ruby-paper", version.ref = "ruby" }

# Gabber
gabber = { module = "me.gabber235:typewriter", version = "0.0.1" }

# Configurations
yaml = { module = "me.carleslc.Simple-YAML:Simple-Yaml", version.ref = "yaml" }
yaml_config = { module = "me.carleslc.Simple-YAML:Simple-Configuration", version.ref = "yaml" }
config_me = { module = "ch.jalu:configme", version = "1.3.0" }

# Triumph Team
triumph_cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version = "2.0.0-SNAPSHOT" }

# Misc
nbt_api = { module = "de.tr7zw:item-nbt-api", version = "2.11.1" }
bstats_bukkit = { module = "org.bstats:bstats-bukkit", version = "3.0.0" }
vault_api = { module = "com.github.MilkBowl:VaultAPI", version = "1.7" }

# Holograms
holographic_displays = { module = "me.filoghost.holographicdisplays:holographicdisplays-api", version = "3.0.0" }
decent_holograms = { module = "com.github.decentsoftware-eu:decentholograms", version = "2.7.8" }

cmi_api = { module = "com.Zrips.CMI:CMI-API", version = "9.3.2.1" }
cmi_lib = { module = "net.Zrips.CMILib:CMI-Lib", version = "1.2.4.5" }

# Placeholders
placeholder_api = { module = "me.clip:placeholderapi", version = "2.11.2" }

# Item Plugins
itemsadder_api = { module = "com.github.LoneDev6:api-itemsadder", version = "3.0.0" }