[versions]
modrinth = "2.8.2"
userdev = "1.5.5"
shadow = "8.1.1"

[plugins]
userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth" }