# Discord: https://discord.gg/crazycrew
# Github: https://github.com/Crazy-Crew
#
# Report Issues: https://github.com/Crazy-Crew/CrazyCrates/issues
# Request Features/Support: https://github.com/orgs/Crazy-Crew/discussions

settings:
  prefix:
    command: "<gradient:#FE5F55:#6b55b5>[CrazyCrates]</gradient> " # The prefix used in front of messages.

  # The language file to use from the locale folder.
  # Supported languages are Spanish(sp), Czech(cz), English(en).
  locale-file: "locale-en.yml"

  verbose-logging: false # Whether you want to have an empty console or not.

  update-checker: true # Whether you want to be notified when an update is published to Modrinth.
  toggle-metrics: true # Whether you want your server statistics to be sent to https://bstats.org/ ( Requires a restart! )
  config-version: 1.1 # DO NOT TOUCH THIS: We use this to identify if the config is outdated.

  # WARNING: If you switch this option to "true", &7 for example will no longer work.
  #
  # You will have to use https://docs.adventure.kyori.net/minimessage/format.html
  # NOTE: This option is a temporary courtesy, &7 at a point might be completely removed.
  #
  # Example of how to use MiniMessage: <gray>Hello <gold>How are you?</gold></gray>
  use-mini-message: false

crate-settings:
  crate-actions:
    # Warning: The log file may cause your server to crash.
    # It is recommended you clear it occasionally.
    # Option will always be set to false by default.
    log-to-file: false
    log-to-console: false # Whether you want to log to console or not.
  preview-menu:
    toggle: true # Whether you want /crates to open a menu or not.
    name: "&b&lCrazy &4&lCrates" # The title of the /crates menu.
    size: 45 # The size of the /crates menu.
  # Whether you want crates to knock you back if you have no keys.
  #
  # Warning: This will be moved to be an option per crate.
  knock-back: true

  keys:
    physical-accepts-virtual-keys: true # Whether physical crates accept virtual keys or not.
    physical-accepts-physical-keys: true # Whether physical crates accept physical keys or not.
    virtual-accepts-physical-keys: true # Whether virtual crates accept physical keys or not.
    inventory-not-empty:
      give-virtual-keys-message: true # Whether to notify the player they were given a virtual key when inventory is not empty.
      give-virtual-keys: true # Whether to give virtual keys to a player if inventory is not empty.
    key-sound:
      name: 'ENTITY_VILLAGER_NO' # This sound will play when a player tries to open a crate without a virtual/physical key.
      # Whether the sound should play or not.
      #
      # Warning: This will be moved to be an option per crate.
      toggle: false

  quad-crate:
    # How long a quad crate should be open?
    #
    # Warning: This will be moved to be an option in QuadCrate files.
    # Moving this will allow each quadcrate to have different timers.
    timer: 300
  disabled-worlds:
    # Whether you want to deny crate usage in X world or not.
    #
    # Warning: This will potentially be moved to be an option per crate for more specific control.
    toggle: true
    worlds: # The list of worlds to deny crate usage in.
      - 'world_nether'

gui-settings:
  buttons:
    menu:
      item: 'COMPASS' # The material of the Menu Button.
      name: '&d&l>> &c&lMenu &d&l<<' # The name of the Menu Button.
      lore: # The lore of the Menu Button.
        - '&7Return to the menu.'
    next:
      item: 'FEATHER' # The material of the Next Button.
      name: '&6&lNext >>' # The name of the Next Button.
      lore: # The lore of the Next Button.
        - '&7&lPage: &b<page>'
    back:
      item: 'FEATHER' # The material of the Back Button.
      name: '&6&l<< Back' # The name of the Back Button.
      lore: # The lore of the Back Button.
        - '&7&lPage: &b<page>'
  filler-items:
    # Whether to fill the gui with an item.
    #
    # Warning: This entire section from here on including gui-customizer is subject to change.
    toggle: false
    item: 'BLACK_STAINED_GLASS_PANE' # The item you wish to use.
    name: ' ' # The name of the item.
    lore: [] # The lore of the item.
  # Place extra items in the gui, If you simply wish to not use this.
  # Set it to customizer: [].
  customizer:
    - 'Slot:1, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:2, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:3, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:4, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:5, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:6, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:7, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:8, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:9, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:10, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:18, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:19, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:27, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:28, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:36, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:37, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:45, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:11, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:12, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:13, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:14, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:15, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:16, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:17, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:20, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:22, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:24, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:26, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:29, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:30, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:31, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:32, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:33, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:34, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:35, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:38, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:39, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:40, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:41, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:42, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:43, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:44, Item:BLACK_STAINED_GLASS_PANE, Name: '