settings:
  # The language file to use from the locale folder.
  # Supported languages are Spanish(sp), Czech(cz) & English(en).
  language-file: 'locale-en.yml'
  # Whether you want to have extra logging enabled.
  verbose: true
  # Whether you want metrics to be enabled.
  toggle-metrics: true
  # Settings related to Data Storage
  data-storage:
    # How the plugin should store data
    #
    # - Your Options
    # | Remote Database Types - You need to supply connection information.
    # |» MySQL *NOT IMPLEMENTED*
    # |» MariaDB ( Recommended over MySQL ) *NOT IMPLEMENTED*
    #
    # | Local Database Types
    # |» H2 *NOT IMPLEMENTED*
    #
    # | Text File Based Storage
    # |» JSON (.json files) *DEFAULT
    storage-method: JSON

    data:
      # Define the address / port for the database.
      # » Default port is used for each one.
      #  MariaDB: 3306
      # » If the port is different, Use "host:port"
      address: localhost
      # The name of the database to use *Must be created beforehand manually.
      database: minecraft
      # The user you use to connect to the database. *root is not recommended!
      username: root
      # The password.
      password: ''

      # What should the name of the table be?
      table-prefix: 'crazycrates_'

      # Don't touch these unless you know what your doing.
      pool-settings:
        max-pool-size: 10
        min-idle: 10
        max-life-time: 1800000 # 30 Minutes
        keep-alive-time: 0
        connection-timeout: 5000 # 5 Seconds
        properties:
          use-unicode: true
          character-encoding: utf8

  # Crate related settings
  crate:
    # If crates should have knock back if they have no keys.
    knock-back: true
    keys:
      # Should a physical crate accept virtual keys?
      physical-crate-accepts-virtual-keys: true
      # Should a virtual crate ( /crates ) accept physical keys?
      virtual-crate-accepts-physical-keys: true
      # Should I give virtual keys if inventory is full?
      give-virtual-keys-with-full-inventory: false
      key-sound:
        # Do you want me to play a sound?
        enabled: false
        # The sound you want to play!
        name: 'ENTITY_VILLAGER_NO'
    quad-crate:
      # I don't know what this is yet.
      timer: 300
    # What worlds do you want Crates to be disabled in?
    disabled-worlds:
      - 'world_nether'