name: '${name}'
main: '${group}.${name}'

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'

bootstrapper: '${group}.PluginStarter'
loader: '${group}.PluginLoader'

dependencies:
  server:
    CMI:
      load: BEFORE
      required: false
      join-classpath: true
    DecentHolograms:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true