name: '${name}'
main: '${group}.CrazyCrates'

version: '${version}'
api-version: '1.20'
description: '${description}'

bootstrapper: '${group}.CrazyStarter'

dependencies:
  server:
    CMI:
      load: BEFORE
      required: false
      join-classpath: false
    DecentHolograms:
      load: BEFORE
      required: false
      join-classpath: false
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: false