name: '${name}'
main: '${group}.CrazyCrates'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

softdepend: [CMI, DecentHolograms, HolographicDisplays, PlaceholderAPI, ItemsAdder, Oraxen]

commands:
  crates:
    description: The base command for Crazy Crates
    aliases: [crazycrates, crazycrate, crate, cc]
  keys:
    description: Views the amount of keys you/others have.
    aliases: [key]

permissions:
  crazycrates.help:
    default: true
    children:
      crazycrates.key: true

  crazycrates.crate-menu:
    default: true

  crazycrates.key:
    default: false

  crazycrates.key-others:
    default: false
    children:
      crazycrates.key: true

  crazycrates.admin-access:
    default: false

  crazycrates.additem:
    default: false

  crazycrates.preview:
    default: false

  crazycrates.list:
    default: false
    children:
      crazycrates.teleport: true

  crazycrates.open:
    default: false

  crazycrates.open-others:
    default: false
    children:
      crazycrates.open: true

  crazycrates.take-key:
    default: false
    children:
      crazycrates.transfer: true

  crazycrates.transfer:
    default: false

  crazycrates.force-open:
    default: false
    children:
      crazycrates.open: true
      crazycrates.open-others: true

  crazycrates.teleport:
    default: false

  crazycrates.give-key:
    default: false

  crazycrates.give-random-key:
    default: false

  crazycrates.give-all:
    default: false
    children:
      crazycrates.give-key: true
      crazycrates.give-random-key: true
      crazycrates.take-key: true
      crazycrates.transfer: true

  crazycrates.set-crate:
    default: false

  crazycrates.reload:
    default: false

  crazycrates.debug:
    default: false

  crazycrates.convert:
    default: false

  crazycrates.schematic-save:
    default: false

  crazycrates.schematic-set:
    default: false

  crazycrates.open.*:
    default: true

  crazycrates.players.*:
    default: false
    children:
      crazycrates.key-others: true
      crazycrates.crate-menu: true
      crazycrates.help: true

  crazycrates.schematic.*:
    default: false
    children:
      crazycrates.schematic-save: true
      crazycrates.schematic-set: true

  crazycrates.admin.*:
    default: false
    children:
      crazycrates.schematic.*: true
      crazycrates.help: true
      crazycrates.convert: true
      crazycrates.debug: true
      crazycrates.set-crate: true
      crazycrates.give-all: true
      crazycrates.force-open: true
      crazycrates.open-others: true
      crazycrates.list: true
      crazycrates.preview: true
      crazycrates.additem: true
      crazycrates.admin-access: true